export const STRINGS = {
  auth: {
    welcomeBack: "Welcome Back",
    signInSubtitle: "Sign in to your wellness account",
    emailOrPhone: "Email or Phone Number",
    emailPlaceholder: "Enter your email or phone",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    forgotPassword: "Forgot Password?",
    signIn: "Sign In",
    signingIn: "Signing in...",
    noAccount: "Don't have an account?",
    createAccount: "Create Account",
    createAccountTitle: "Create Account",
    joinCommunity: "Join our wellness community",
    fullName: "Full Name *",
    fullNamePlaceholder: "Enter your full name",
    age: "Age",
    agePlaceholder: "Enter your age",
    phone: "Phone Number",
    phonePlaceholder: "Enter your phone number",
    email: "Email Address *",
    emailAddress: "Email Address",
    confirmPassword: "Confirm Password *",
    confirmPasswordPlaceholder: "Re-enter your password",
    chooseRole: "Choose Your Role *",
    haveAccount: "Already have an account?",
    resetPassword: "Reset Password",
    sendResetEmail: "Send Reset Email",
    sending: "Sending...",
    verifyOtp: "Verify OTP",
    verifying: "Verifying...",
    backToSignIn: "← Back to Sign In",
    otpSent: "OTP Sent!",
    enterOtp: "Enter 6-Digit OTP",
    otpPlaceholder: "000000",
    resendOtp: "Didn't receive OTP? Resend",
    setNewPassword: "Set New Password",
    newPassword: "New Password",
    newPasswordPlaceholder: "Enter new password",
    resetting: "Resetting...",
    resetSuccess: "Password Reset Successfully!",
  },

  validation: {
    emailRequired: "Please enter your email address",
    emailInvalid: "Please enter a valid email address",
    emailNotRegistered: "Email ID not registered.",
    passwordRequired: "Please enter your password",
    passwordMinLength: "Password must be at least 6 characters long",
    passwordsDoNotMatch: "Passwords do not match",
    fillAllFields: "Please fill in all required fields",
    identifierRequired: "Please enter email/phone and password.",
    acceptConsent: "Please accept the consent and privacy policy to continue",
    otpInvalid: "Please enter a valid 6-digit OTP",
  },

  common: {
    loading: "Loading...",
    error: "Something went wrong",
    retry: "Retry",
    cancel: "Cancel",
    save: "Save",
    close: "Close",
    success: "Success",
    networkError: "Network error — please check your connection.",
  },

  brand: {
    name: "HiWox",
    tagline: "Your wellness companion",
    footerTagline: "Your wellness journey starts here",
  },
} as const;
